name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-08-01
        target: wasm32-unknown-unknown
        override: true
    - name: Build contracts
      run: |
        cd 7_ink_contract/erc20
        cargo install cargo-contract --vers ^0.14 --force --locked
        cargo contract build --release
    - name: Run tests
      run: |
        cd 7_ink_contract/erc20
        cargo contract test
