name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-08-01
        target: wasm32-unknown-unknown
        override: true
    - name: Build Kitties
      run: |
        cd 4_kitties
        cargo build --release
    - name: Run tests
      run: |
        cd 4_kitties 
        cargo test
